"""change-area_m2-to-float

Revision ID: ed3c8b876611
Revises: 2f777324a2dc
Create Date: 2026-05-10 15:55:42.840453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3c8b876611'
down_revision: Union[str, Sequence[str], None] = '2f777324a2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aois', 'area_m2',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aois', 'area_m2',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
